### ISSUE TITLE
Remove djunk ? 

### ISSUE THREAD

**Issue by spapas** [caltechads/wagtail-jetstream#2]
There's a line `from djunk.middleware import get_current_request` on blocks.py. I tried installing djunk but it seems to *not include* the middleware module at all (https://github.com/jordaneremieff/djunk/tree/main/djunk). Also the djunk app seems to not be something that anybody would want to re-use except its author.

Instead I recommend using the django-tools library (https://github.com/jedie/django-tools/) that also has a similar threadlocals middleware (that's confirmed to work good):

https://github.com/jedie/django-tools/blob/main/django_tools/middlewares/ThreadLocal.py

**Comment by cnk** [comment]
Sorry, djunk is one of our packages that is not open-sourced. The one method used by jetstream is included below. But my recommendation is that you fork this repository and remove `FeatureCustomizedStreamBlock` replacing all mentions of it with Wagtail's StreamBlock. That will remove the dependency on our `djunk` package AND on our non-open-source features registry.

```
from crequest.middleware import CrequestMiddleware

class NoCurrentRequestException(Exception):
    pass

def get_current_request(default=None, silent=True, label='__DEFAULT_LABEL__'):
    request = CrequestMiddleware.get_request(default)
    if request is None and not silent:
        raise NoCurrentRequestException(
            "{} failed because there is no current request. Try using djunk.utils.FakeCurrentRequest.".format(label)
        )
    return request

```

**Comment by spapas** [comment]
Hey @cnk thanks for answering. I understand why you may not want to open source your djunk lib. However please notice that unless you use a different way to get the current request people won't be able to actually use this package *unless* they fork it (so they'll remove the ``from djunk.middleware import get_current_request``. 

So I'd recommend to do something like:

```
try:
  from djunk.middleware import get_current_request
except:
  get_current_request = lambda: None
```


This way the library will keep working for you using the private djunk package but will also work fine for people that don't have it.

**Comment by cnk** [comment]
That would fix this particular import but get_current_request is only used in FeatureCustomizedStreamBlock and making that generally installable is much more difficult - as you noted in issue #3. If I figure out a way to remove that from an open-source release without interfering with our existing projects, I'll include this in that refactoring.

**Comment by spapas** [comment]
> There's an even simpler solution then. Move `from djunk.middleware import get_current_request` from the top level inside the functions it's used; see https://github.com/caltechads/wagtail-jetstream/pull/9

Actually it ain't working :( it seems that the child_blocks() property is called from the class initialization so it still throws the exception.

**Comment by spapas** [comment]
I tried changing `from djunk.middleware import get_current_request` to this:

```
try:
    from djunk.middleware import get_current_request
except ImportError:
    get_current_request = lambda: None
```

and it works for my project.
