### ISSUE TITLE
Clarify (or include) modernizr version

### ISSUE THREAD

**Issue by spapas** [caltechads/wagtail-jetstream#4]
Right now I'm using https://cdnjs.cloudflare.com/ajax/libs/modernizr/2.8.3/modernizr.min.js and seems to be working. Is this the correct one ? I'd recommed to include the correct file with the project (similar to how you include `jetstream/js/layouts.js`)

**Comment by cnk** [comment]
Looks like the projects we use this in have a custom file using Modernizr 3.6.0 as the base. It would be awkward for us to include this in the project but I'll update the README with notes on what features are expected to be available from Modernizr.

You can download a feature set matching ours from https://modernizr.com/download/?cssanimations-csstransitions-addtest-mq-prefixed-prefixes-setclasses

**Comment by spapas** [comment]
Excellent ! Thank you @cnk 

Maybe it would be nice if you added that link to the README (https://github.com/caltechads/wagtail-jetstream#block-types) so other people may also get the correct modernzr ?
