### ISSUE TITLE
Clarify which css / scss files to include

### ISSUE THREAD

**Issue by spapas** [caltechads/wagtail-jetstream#5]
It seems that we need to include some styling to our pages for this lib to work properly (i.e colors are missing). 

However I am *not* familiar with scss at all and I don't know which files to include. 

I followed the instructions from here https://www.accordbox.com/blog/how-use-scss-sass-your-django-project-python-way/ and added this:

```html
{% compress css %}
            <link type="text/x-scss" href="{% static 'jetstream/css/layouts.scss' %}" rel="stylesheet" media="screen">
        {% endcompress %}
```

on my base.html. It seems to be working now however I can't be sure if I'm missing anything ?

**Comment by cnk** [comment]
Yes that is the way to include the custom CSS expected for this project. That layouts file includes common.scss, which in turn includes global.scss where the colors are defined. You should see the compiled file when you look in your browser console. If you change the first line to `{% compress css layouts.css %}` I think that should give you a more readable file name (though it will also increase browser caching so perhaps do that after you have changed most things you want to change)

**Comment by spapas** [comment]
Excellent thank you!
