### ISSUE TITLE
Could you explain the difference between `BaseTwoColumnSubBlock` and `BaseTwoColumnBlock`

### ISSUE THREAD

**Issue by spapas** [caltechads/wagtail-jetstream#6]
The class docstrings of `BaseTwoColumnSubBlock ` say 

> Duplicate of BaseTwoColumnBlock without the sub block to avoid recursion.

but I can't understand that nor there seems to actually be any difference between these two classes

**Comment by spapas** [comment]
Also please notice that  there's a `BaseFourColumnBlock` but *not* a `BaseFourColumnSubBlock`

**Comment by cnk** [comment]
Sorry `BaseTwoColumnSubBlock` is to support more code you can't see. BaseTwoColumnBlock is the original implementation but then in our project we wanted to have [nested 2 column blocks](https://qa.sites.caltech.edu/two-columns/two-columns-two-column-within-two-column) (so you could vary the height and widths independently). So we needed BaseTwoColumnSubBlock so we could include that in the left and right columns of BaseTwoColumnBlock. So in our custom BaseTwoColumnBlock the left and right columns are defined as: 

```
class TwoColumnBlock(BaseTwoColumnBlock):
    left_column = FeatureCustomizedStreamBlock(
        COLUMN_PERMITTED_BLOCKS + [get_block_tuple(BaseTwoColumnSubBlock())]
	)
    right_column = FeatureCustomizedStreamBlock(
        COLUMN_PERMITTED_BLOCKS + [get_block_tuple(BaseTwoColumnSubBlock())]
	)
```

I believe this nesting of basically the same block is also the reason for the `get_block_tuple` method so we could set the same block name for 2 blocks and then use that in our templates - see the comment in jetstream/utils.py.

Unless you need this nesting, please just ignore `BaseTwoColumnSubBlock`. 

Also note that deep nesting makes the wagtail admin SUPER SLOW when template caching is turned off. Not a problem when the site is in production but it can be agonizing if you are developing on a machine with slow file access (such as certain situations with Docker + mounted volumes)

**Comment by spapas** [comment]
Thank you for the great answer!
